spring.application.name=doorapp
spring.security.user.name=user
spring.security.user.password=user

spring.datasource.url=jdbc:postgresql://localhost:5432/ShubhamBoot
spring.datasource.username = postgres
spring.datasource.password = shubham2375

#spring.main.allow-circular-references=true
#for the file handling from the request
spring.servlet.multipart.enabled =true
spring.servlet.multipart.max-file-size =10MB
spring.servlet.multipart.max-request-size =10MB
file.upload-dir=src/main/uploads/

